name: Build

on:
  push:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build sysroot for ${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [armv7, aarch64, riscv64, s390x, ppc64le]

    steps:
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu20.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          setup: |
            mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          install: |
            apt-get update -q -y
            apt-get install -q -y --no-install-recommends \
              build-essential \
              ca-certificates \
              curl \
              git \
              libssl-dev \
              pkg-config \
              python3 \
              python3-pip \
              python3-setuptools \
              python3-wheel \
              sudo \
              unzip \
              wget \
              zip

          shell: /bin/bash

          run: |
            cd /
            shopt -s extglob
            tar c -zf /artifacts/sysroot-${{ matrix.arch }}.tar.gz *(bin|lib|include) usr/*(bin|lib|include) usr/local/*(bin|lib|include)

      - uses: actions/upload-artifact@v3
        with:
          name: sysroot
          path: artifacts/sysroot-${{ matrix.arch }}.tar.gz
