name: Build

on:
  push:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          install: |
            apt-get update -q -y
            apt-get install -q -y --no-install-recommends \
              build-essential \
              ca-certificates \
              curl \
              git \
              libssl-dev \
              pkg-config \
              python3 \
              python3-pip \
              python3-setuptools \
              python3-wheel \
              sudo \
              unzip \
              wget \
              zip

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            cd /
            tar c -zf /artifacts/sysroot.tar.gz bin lib include usr/bin usr/lib usr/include

      - uses: actions/upload-artifact@v3
        with:
          name: sysroot
          path: /artifacts/sysroot.tar.gz
